name: Bishoto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2276
title: Bishop Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.022298423806205392
  saturation: 0.6875
  rhythmicContrast: 0.23321019439026713
purpose: []
